Repository marrlab/DomainLab, pull requests merged in 2023-09, with the labels that each got.

#350 fix chain_node_builder and diva test func
  domainlab/compos/pcr/request.py
  domainlab/compos/vae/compos/encoder_xyd_parallel.py
  domainlab/compos/vae/utils_request_chain_builder.py
  domainlab/compos/vae/zoo_vae_builders_classif.py
  tests/test_mk_exp_diva.py
Labels: priority

#382 new slurm qos
  examples/yaml/slurm/config.yaml
Labels: priority

#398 felix_tensorboard
  domainlab/algos/trainers/fbopt_alternate.py
Labels: fbopt

#404 prevent parameter doubling in benchmark yaml
  domainlab/exp_protocol/run_experiment.py
  tests/test_run_experiment.py
Labels: fbopt

#433 change model selection back to validation accuracy
  domainlab/algos/msels/c_msel_bang.py
  domainlab/algos/observers/c_obvisitor_cleanup.py
  domainlab/algos/trainers/train_fbopt.py
  domainlab/arg_parser.py
Labels: fbopt

#445 use task multiplier in abstract model only
  domainlab/models/a_model.py
  domainlab/models/model_vae_xyd_classif.py
Labels: bug

#453 fixed wrong setting for msel_tr_loss
  examples/benchmark/benchmark_fbopt_pacs_full.yaml
Labels: bug, fbopt

#455 make it easier to debug crashes
  domainlab/exp_protocol/run_experiment.py
Labels: enhancement, fbopt

#426 Fbopt plot penalized
  domainlab/algos/trainers/fbopt_alternate.py
Labels: fbopt

#459 Fbopt recon multiplier
  domainlab/models/model_diva.py
  domainlab/models/model_hduva.py
  run_fbopt_diva_cpu.sh
  run_fbopt_hduva_cpu.sh
Labels: bug

#311 fishr
  domainlab/algos/trainers/a_trainer.py
  domainlab/algos/trainers/train_fishr.py
  domainlab/algos/trainers/zoo_trainer.py
  domainlab/models/a_model.py
  domainlab/models/a_model_classif.py
  domainlab/models/model_deep_all.py
  domainlab/tasks/a_task.py
  domainlab/tasks/b_task.py
  poetry.lock
  pyproject.toml
  requirements.txt
  test_fishr.sh
  tests/test_fishr.py
Labels: priority

#465 no need to sample gamma_d in diva since it is registered in mu already
  examples/benchmark/benchmark_fbopt_pacs_full.yaml
Labels: enhancement, priority, benchmark, fbopt

#470 Update model_dann.py: invert the sign of the regularization loss of dann so that minimization still make sense
  domainlab/models/model_dann.py
Labels: enhancement, fbopt

#468 add slurm_id to model name as suffix Update exp_utils.py
  domainlab/compos/exp/exp_utils.py
Labels: paper_jmlr_joss

#460 Fbopt setpoint controller
  domainlab/algos/trainers/fbopt_alternate.py
  domainlab/algos/trainers/fbopt_setpoint_ada.py
  domainlab/algos/trainers/train_fbopt.py
  run_fbopt.sh
  run_fbopt_dann.sh
  run_fbopt_diva_cpu.sh
Labels: bug, enhancement, priority, in progress, fbopt
